### ISSUE TITLE
Unclear how to run anytype-heart

### ISSUE THREAD

**Issue by SamBouwer** [anyproto/anytype-heart#225]
In the docs of the other any-parts it's written how to eventually run the built go apps. Unfortunately I am not experienced enough to recognize how to run anytype-heart once building is completed (for a particular platform). Any help is appreciated so can continue working on the docker images I'm making to make selfhosting easier for others.

**Comment by fuksman** [comment]
Hi @SamBouwer, you don't need to run it separately. The built version of `anytype-heart` acts as a middleware library and is distributed *inside* the apps. 
Also, since `anytype-heart` is a part of the applications and not a part of the infrastructure, there is no need to have it inside a Docker image.

**Comment by SamBouwer** [comment]
@fuksman thanks for clarifying! Now I understand the docs better :) . I'll update my Dockerfile and maybe make a pull request to add this information to the Anytype tech docs. Issue closed :)
